# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='recyclinginfomation',
            options={'verbose_name_plural': 'Recycle Infos'},
        ),
        migrations.AlterField(
            model_name='component',
            name='main_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycleapp.Component'),
        ),
    ]
