# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0002_auto_20171028_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catetory',
        ),
    ]
