# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0003_remove_product_catetory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
    ]
