# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0004_remove_material_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycleapp.Category')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycleapp.Material')),
            ],
        ),
        migrations.CreateModel(
            name='MinorComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycleapp.Category')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycleapp.Material')),
            ],
        ),
        migrations.CreateModel(
            name='MinorRecyclingInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycleapp.MinorComponent')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycleapp.Country')),
            ],
            options={
                'verbose_name_plural': 'Minor Recycle Infos',
            },
        ),
        migrations.RenameModel(
            old_name='RecyclingInfomation',
            new_name='MainRecyclingInfomation',
        ),
        migrations.RemoveField(
            model_name='component',
            name='category',
        ),
        migrations.RemoveField(
            model_name='component',
            name='main_component',
        ),
        migrations.RemoveField(
            model_name='component',
            name='material',
        ),
        migrations.AlterModelOptions(
            name='mainrecyclinginfomation',
            options={'verbose_name_plural': 'Main Recycle Infos'},
        ),
        migrations.AlterField(
            model_name='mainrecyclinginfomation',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycleapp.MainComponent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycleapp.MainComponent'),
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.AddField(
            model_name='maincomponent',
            name='minor_components',
            field=models.ManyToManyField(to='recycleapp.MinorComponent'),
        ),
    ]
