# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycleapp', '0004_remove_material_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
